// tinacms-fumadocs-pkg:wired — generated by `tinacms-fumadocs-pkg init`.
// Your previous docs page (if any) was saved next to this as page.tsx.orig;
// re-add any custom toolbar / OG bits from it. Fumadocs still does ALL the
// rendering here; TinaCMS only edits the same .mdx file on disk.
import { source } from '@/lib/source';
import {
  DocsBody,
  DocsDescription,
  DocsTitle,
} from 'fumadocs-ui/layouts/docs/page';
import { notFound } from 'next/navigation';
import { getMDXComponents } from '@/components/mdx';
import type { Metadata } from 'next';
import { createRelativeLink } from 'fumadocs-ui/mdx';
// --- TinaCMS contextual editing (does NOT replace the Fumadocs render) ---
import { tinaField } from '@tinacms/bridge/tina-field';
import {
  prepareTinaForm,
  withTinaMarkers,
  TinaEditBridge,
} from 'tinacms-fumadocs-pkg';
// Stateful <DocsPage> whose "On this page" toc tracks live heading edits inside
// the admin iframe (renders the same static toc for real visitors).
import { TinaDocsPage } from 'tinacms-fumadocs-pkg/live-toc';
// Client boundary that binds the REAL Fumadocs components to the live preview
// (a Server Component can't pass the `getComponents` function prop directly).
// This file is emitted next to page.tsx by `tinacms-fumadocs-pkg init`.
import { TinaLiveBodyClient } from '@/components/tina-live-body';
import { client } from '@/tina/__generated__/client';
import type { DocsQuery } from '@/tina/__generated__/types';

export default async function Page(props: PageProps<'/docs/[[...slug]]'>) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;

  // Fetch the SAME file via the Tina client only for edit metadata + the form
  // payload. The body below stays 100% Fumadocs. Degrades to plain Fumadocs if
  // the local Tina server is not running.
  const tina = await client.queries
    .docs({ relativePath: page.path }, { fetchOptions: { cache: 'no-store' } })
    .then((res) => prepareTinaForm<DocsQuery>(res))
    .catch(() => null);
  const doc = tina?.data.docs;

  const titleField = doc ? tinaField(doc, 'title') : undefined;
  const bodyField = doc ? tinaField(doc, 'body') : undefined;

  // Fumadocs' normal component map, with tina markers wrapped on top when editing.
  const baseComponents = getMDXComponents({
    a: createRelativeLink(source, page),
  });
  const components = bodyField
    ? withTinaMarkers(baseComponents, bodyField)
    : baseComponents;

  return (
    <TinaDocsPage toc={page.data.toc} full={page.data.full}>
      {/* Form payload @tinacms/bridge discovers to open the sidebar form. */}
      {tina ? (
        <>
          <div
            data-tina-form={JSON.stringify(tina.payload)}
            data-tina-primary=""
            style={{ display: 'none' }}
          />
          <TinaEditBridge formId={tina.id} />
        </>
      ) : null}

      {/* Title is a leaf string field -> safe to live-patch in place. */}
      <DocsTitle data-tina-field={titleField} data-tina-leaf="true">
        {page.data.title}
      </DocsTitle>
      <DocsDescription className="mb-0">
        {page.data.description}
      </DocsDescription>

      {/* Body stays a Fumadocs render. Inside the admin iframe, TinaLiveBody
          takes over with a CLIENT-side keystroke-live preview that renders the
          REAL Fumadocs components (no placeholder); everywhere else (and on the
          editor's first paint) it renders the real <MDX/> verbatim. */}
      <DocsBody data-tina-field={bodyField}>
        {tina ? (
          <TinaLiveBodyClient formId={tina.id} bodyField={bodyField}>
            <MDX components={components} />
          </TinaLiveBodyClient>
        ) : (
          <MDX components={components} />
        )}
      </DocsBody>
    </TinaDocsPage>
  );
}

export function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(
  props: PageProps<'/docs/[[...slug]]'>,
): Promise<Metadata> {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  return {
    title: page.data.title,
    description: page.data.description,
  };
}
