// tinacms-fumadocs-pkg:wired — generated by `tinacms-fumadocs-pkg init`.
// Your previous docs page (if any) was saved next to this as page.tsx.orig;
// re-add any custom toolbar / OG bits from it. Fumadocs still does ALL the
// rendering here; TinaCMS only edits the same .mdx file on disk.
import { source } from '@/lib/source';
import {
  DocsBody,
  DocsDescription,
  DocsPage,
  DocsTitle,
} from 'fumadocs-ui/layouts/docs/page';
import { notFound } from 'next/navigation';
import { getMDXComponents } from '@/components/mdx';
import type { Metadata } from 'next';
import { createRelativeLink } from 'fumadocs-ui/mdx';
// --- TinaCMS contextual editing (does NOT replace the Fumadocs render) ---
import { tinaField } from '@tinacms/bridge/tina-field';
import {
  prepareTinaForm,
  withTinaMarkers,
  TinaEditBridge,
  TinaIslandBody,
} from 'tinacms-fumadocs-pkg';
import { tinaIslandUrl, getIslandSeedHtml } from 'tinacms-fumadocs-pkg/island';
import { previewComponents } from 'tinacms-fumadocs-pkg/preview';
import { client } from '@/tina/__generated__/client';
import type { DocsQuery } from '@/tina/__generated__/types';
import { createHash } from 'node:crypto';

export default async function Page(props: PageProps<'/docs/[[...slug]]'>) {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  const MDX = page.data.body;

  // Fetch the SAME file via the Tina client only for edit metadata + the form
  // payload. The body below stays 100% Fumadocs. Degrades to plain Fumadocs if
  // the local Tina server is not running.
  const tina = await client.queries
    .docs({ relativePath: page.path }, { fetchOptions: { cache: 'no-store' } })
    .then((res) => prepareTinaForm<DocsQuery>(res))
    .catch(() => null);
  const doc = tina?.data.docs;

  const titleField = doc ? tinaField(doc, 'title') : undefined;
  const bodyField = doc ? tinaField(doc, 'body') : undefined;
  const islandUrl = tina ? tinaIslandUrl(params.slug) : undefined;

  // SSR the SAVED body through the SAME preview map the island route uses, so
  // the first editor frame matches every keystroke refresh. remountKey hashes
  // the saved body so the live container re-seeds cleanly after a save.
  let islandSeedHtml: string | undefined;
  let islandRemountKey: string | undefined;
  if (islandUrl) {
    const raw = await page.data.getText('raw');
    islandRemountKey = createHash('sha1').update(raw).digest('hex').slice(0, 16);
    islandSeedHtml = await getIslandSeedHtml({
      getRawText: async () => raw,
      getComponents: () => previewComponents(getMDXComponents()),
      path: page.path,
    });
  }

  // Fumadocs' normal component map, with tina markers wrapped on top when editing.
  const baseComponents = getMDXComponents({
    a: createRelativeLink(source, page),
  });
  const components = bodyField
    ? withTinaMarkers(baseComponents, bodyField)
    : baseComponents;

  return (
    <DocsPage toc={page.data.toc} full={page.data.full}>
      {/* Form payload @tinacms/bridge discovers to open the sidebar form. */}
      {tina ? (
        <>
          <div
            data-tina-form={JSON.stringify(tina.payload)}
            data-tina-primary=""
            style={{ display: 'none' }}
          />
          <TinaEditBridge formId={tina.id} />
        </>
      ) : null}

      {/* Title is a leaf string field -> safe to live-patch in place. */}
      <DocsTitle data-tina-field={titleField} data-tina-leaf="true">
        {page.data.title}
      </DocsTitle>
      <DocsDescription className="mb-0">
        {page.data.description}
      </DocsDescription>

      {/* Body stays a Fumadocs render. Inside the admin iframe, TinaIslandBody
          takes over with the keystroke-live preview; everywhere else it renders
          the real <MDX/> verbatim. */}
      <DocsBody data-tina-field={bodyField}>
        {islandUrl ? (
          <TinaIslandBody
            islandUrl={islandUrl}
            initialHtml={islandSeedHtml ?? ''}
            remountKey={islandRemountKey}
            bodyField={bodyField}
          >
            <MDX components={components} />
          </TinaIslandBody>
        ) : (
          <MDX components={components} />
        )}
      </DocsBody>
    </DocsPage>
  );
}

export function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata(
  props: PageProps<'/docs/[[...slug]]'>,
): Promise<Metadata> {
  const params = await props.params;
  const page = source.getPage(params.slug);
  if (!page) notFound();

  return {
    title: page.data.title,
    description: page.data.description,
  };
}
